### PR TITLE
Update PRIMA.jl for the updated artifact

### PR DESCRIPTION
**Pull request by amontoison**
I generated the wrappers with Clang.jl last week (https://github.com/libprima/prima/pull/62),
I propose to merge everything in this repository.

### CODE REVIEW

**Comment by emmt** [comment]
Sorry I pushed a lots of changes (mostly documentation) before I realized that you have made this PR.

In the mean time, I have commented in https://github.com/libprima/prima/pull/62#issuecomment-1731163163 about the needs of a separate repository for the Julia interface. 

I'll try to review your proposed changes as soon as possible.

**Comment by emmt** [comment]
OK if I understood well, the subdirectory `gen` contains code to help building the `src/wrappers.jl` file that implement all the low-level interface to the PRIMA library. In its current state, the produced src/wrappers.jl` has to be edited by hand (what you have done) to eliminate some definitions and replace  function pointer types by `Ptr{Cvoid}` and push the changes.

Thus, the code in `gen` is mostly for us, the developpers, in the sense that it is not meant to be part of the build stage when PRIMA.jl is installed by some end-user. 

I think all this is very good idea. It spares the end-user installing and loading heavy package such as `Clang.jl`. Parts of the wrapper that can be written automatically will be easy to update while we keep our hands on the other parts to fix what has been done by `Clang.jl` (which is powerful but not always do exactly what we want). Since the generated and edited code is part of the repoitory, we can always follows changes in the end-product (not just in the generator). I seriously think that I will propagate this sort of tricks in the other packages where I use `Clang.jl`. 

As was done before your proposed changes, I would like to "simpify" the names of the symbols (such as enumerayion constants) that may be useful for the end-user. These will not be exported so the package module prefix to avoid ambiguities, for example currently `PRIMA.SMALL_TR_RADIUS` wheras with the generated wraper ``PRIMA.PRIMA_SMALL_TR_RADIUS`. This can be done automatically (by making string/regex substitutions in the auto-genrated code) or by hand.

**Comment by emmt** [comment]
Merge done, I just had to make a few fixes (https://github.com/emmt/PRIMA.jl/commit/cc5afd3a793a26973381bc8438880c8b9e359bf9).

Thanks for all this!

**Comment by amontoison** [comment]
Sorry for not answering ealier @emmt. In general I add a `rewriter.jl` in the `gen` folder such that we don't edit by hand the wrappers generated by Clang.jl.
I have an example of [rewriter.jl](https://github.com/JuliaSmoothOptimizers/HSL.jl/blob/main/gen/rewriter.jl) in HSL.jl. 
I will open a PR tonight.

**Comment by amontoison** [comment]
You were faster than me, you already added the [string/regex substitutions](https://github.com/emmt/PRIMA.jl/blob/main/gen/wrapper.jl#L23-L42).

**Comment by emmt** [comment]
Yes, I did that some time ago. Sorry I didn't mention it specifically. I just wrote that:

> Merge done, I just had to make a few fixes ([cc5afd3](https://github.com/emmt/PRIMA.jl/commit/cc5afd3a793a26973381bc8438880c8b9e359bf9)).

Shall we close this?

**Pull request merged**
